graphik-galaxy/src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductsRepository::class)]
class Products
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $taille = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $public_cible = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $genre = null;

    #[ORM\Column(length: 255)]
    private ?string $images = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;


    /**
     * @var Collection<int, Commentaires>
     */
    #[ORM\OneToMany(targetEntity: Commentaires::class, mappedBy: 'products')]
    private Collection $commentaire;

    #[ORM\Column]
    private ?int $stocks = null;

    /**
     * @var Collection<int, CommandeProduits>
     */
    #[ORM\OneToMany(targetEntity: CommandeProduits::class, mappedBy: 'produits')]
    private Collection $commandeProduits;

    public function __construct()
    {
        $this->commentaire = new ArrayCollection();
        $this->commandeProduits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getTaille(): ?string
    {
        return $this->taille;
    }

    public function setTaille(?string $taille): static
    {
        $this->taille = $taille;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getPublicCible(): ?string
    {
        return $this->public_cible;
    }

    public function setPublicCible(?string $public_cible): static
    {
        $this->public_cible = $public_cible;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(string $images): static
    {
        $this->images = $images;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }


    /**
     * @return Collection<int, Commentaires>
     */
    public function getCommentaire(): Collection
    {
        return $this->commentaire;
    }

    public function addCommentaire(Commentaires $commentaire): static
    {
        if (!$this->commentaire->contains($commentaire)) {
            $this->commentaire->add($commentaire);
            $commentaire->setProducts($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): static
    {
        if ($this->commentaire->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getProducts() === $this) {
                $commentaire->setProducts(null);
            }
        }

        return $this;
    }

    public function getStocks(): ?int
    {
        return $this->stocks;
    }

    public function setStocks(int $stocks): static
    {
        $this->stocks = $stocks;

        return $this;
    }



    /**
     * @return Collection<int, CommandeProduits>
     */
    public function getCommandeProduits(): Collection
    {
        return $this->commandeProduits;
    }

    public function addCommandeProduit(CommandeProduits $commandeProduit): static
    {
        if (!$this->commandeProduits->contains($commandeProduit)) {
            $this->commandeProduits->add($commandeProduit);
            $commandeProduit->setProduits($this);
        }

        return $this;
    }

    public function removeCommandeProduit(CommandeProduits $commandeProduit): static
    {
        if ($this->commandeProduits->removeElement($commandeProduit)) {
            // set the owning side to null (unless already changed)
            if ($commandeProduit->getProduits() === $this) {
                $commandeProduit->setProduits(null);
            }
        }

        return $this;
    }


}

graphik-galaxy/src/Controller/ProductsController.php
<?php

namespace App\Controller;

use App\Repository\ProductsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ProductsController extends AbstractController
{
    #[Route('/products/{categories}', name: 'app_products')]
    public function index(ProductsRepository $productsRepository, $categories): Response
    {

        $css = $categories == 'Goodies' ? 'ban-goodies' : ($categories == 'Comics' ? 'ban-comics' : ($categories == 'Mangas' ? 'ban-mangas' : 'ban-tout'));
        if ($categories != 'tout') {
            $produits = $productsRepository->findBy(['categorie' => $categories]);
        } else {
            $produits = $productsRepository->findAll();
        }
        if ($categories == 'tout') {
            $categories = 'Produits';
        }
        return $this->render('products/index.html.twig', [
            'controller_name' => 'ProductsController',
            'produits' => $produits,
            'classe_banniere' => $css,
            'categorie' => $categories,

        ]);
    }
}

graphik-galaxy/templates/products/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ categorie }}
{% endblock %}

{% block body %}
	<div id="full">

		<div class="main">

			<div class="{{ classe_banniere }} banner_size" id="haut">
				<h1 id="products_titles">Tous nos
					{{categorie}}</h1>
			</div>


			<div id="explications-pages">
				{% if categorie =="Mangas" %}

					<p>Art narratif japonais mêlant illustration et texte,Le manga, a conquis le monde grâce à sa diversité de genres et son style unique. En France, il s'est implanté dans les années 1990, devenant rapidement un pilier de la culture populaire, porté par des succès comme Dragon Ball ou Naruto. Graphik-Galaxy, passionné par cet univers, sélectionne minutieusement les meilleurs mangas en collaborant avec des éditeurs renommés et en suivant les tendances mondiales pour offrir des œuvres incontournables et des pépites à ses clients.</p>

				{% elseif categorie =="Comics" %}

					<p>
						Les comics, véritables mythes modernes venus des États-Unis, ont forgé des légendes immortelles comme Spider-Man, Batman ou les Avengers, incarnant des récits épiques de courage, de justice et de lutte contre les ténèbres. En France, leur ascension fulgurante dans les années 2000, portée par des adaptations cinématographiques spectaculaires, a transformé ces héros en icônes universelles. Graphik-Galaxy, gardien de cet univers grandiose, déniche les meilleures pépites en collaborant avec les plus grands éditeurs, suivant les sagas mythiques et les révolutions contemporaines. Ici, chaque page devient une porte vers l’aventure, capturant l’imaginaire des lecteurs en quête de grandeur.</p>

				{% elseif categorie == "Goodies" %}

					<p>
						Les goodies geeks, symboles tangibles des univers imaginaires, incarnent la passion des fans pour les mondes fantastiques et futuristes. En France, ces objets dérivés – figurines, posters, accessoires – ont pris leur envol avec l'essor de la pop culture, transformant les simples admirateurs en véritables collectionneurs. Graphik-Galaxy, explorateur des trésors geeks, parcourt les tendances mondiales et collabore avec les créateurs les plus influents pour offrir des pièces d’exception. Chaque article devient un fragment d’épopée, permettant aux fans de donner vie à leurs héros et à leurs mondes préférés dans leur quotidien.</p>

				{% else %}

					<p>Graphik-Galaxy, temple de la culture geek, réunit sous un même toit les mangas légendaires, les comics mythiques et les goodies emblématiques qui célèbrent les univers fantastiques. Chaque produit, minutieusement sélectionné, raconte une histoire épique : des aventures palpitantes des héros japonais, aux récits grandioses des justiciers américains, en passant par des objets dérivés qui donnent vie à ces mondes extraordinaires. En collaborant avec les plus grands éditeurs et créateurs, Graphik-Galaxy garantit une collection exceptionnelle où chaque pièce devient un fragment d’imaginaire. Ici, la passion geek prend une forme tangible, prête à conquérir l'âme de ses fans.</p>

				</div>
			{% endif %}
			<div class="row">
				<div id="input-search-taille" class="col-md-6 offset-md-3">
					<input type="text" id="searchInput" class="form-control mb-4" placeholder="Filtrer votre Recherche..." autocomplete="off">

				</div>
			</div>


			<div id="produits_page">
				{% for produit in produits %}

					<div class="produits_blocks">
						<div class="produit">
							<a href="{{path('app_details', {id: produit.id})}}"><img src="{{asset('assets/img/' ~ produit.categorie ~ '/' ~ produit.images)}}" alt="{{produit.nom}}" class="produit-image"></a>

							<h4 class="produit-nom">{{produit.nom}}</h4>
							<h6 class="produit-prix">{{produit.prix}}€</h6>
							<div class="boutons_produits">


								<button class="bouton">
									<a href="{{path('app_details', {id: produit.id})}}">details</a>
								</button>

								{%if produit.stocks > 0 %}


									<button class="bouton add_panier" onclick="ajoutPanier(event, {{produit.id}})">ajout panier</button>
								{% else %}
									<button class="btn btn-secondary" disabled style="opacity: 0.6; cursor: not-allowed;">
										Indisponible
									</button>
								{% endif %}


							</div>

						</div>
					</div>
				{% endfor %}
			</div>


			<a href="#haut">retour en haut</a>

		</div>
	</div>
</div>{% endblock %}